apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: test-rhoai-demo-app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-rhoai-demo-app 
  name: test-rhoai-demo-app
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: test-rhoai-demo-app 
